// <auto-generated />
using GestaoEstoque.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoEstoque.Infrastructure.Persistence.Migrations
{

    partial class StockTransfers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.SaldoLocal", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<int>("ProdutoId").HasColumnType("int");
                b.Property<int?>("PosicaoEstoqueId").HasColumnType("int");
                b.Property<decimal>("Quantidade").HasPrecision(13, 3).HasColumnType("decimal(13,3)");
                b.Property<decimal>("Reservado").HasPrecision(13, 3).HasColumnType("decimal(13,3)");
                b.Property<byte[]>("Versao").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                b.HasKey("Id"); b.HasIndex("PosicaoEstoqueId");
                b.HasIndex("ProdutoId").IsUnique().HasDatabaseName("IX_SaldosLocais_ProdutoSemLocal").HasFilter("[PosicaoEstoqueId] IS NULL");
                b.HasIndex("ProdutoId", "PosicaoEstoqueId").IsUnique().HasFilter("[PosicaoEstoqueId] IS NOT NULL");
                b.ToTable("SaldosLocais", (string)null, t => t.HasCheckConstraint("CK_SaldosLocais_Quantidades", "[Quantidade] >= 0 AND [Reservado] >= 0 AND [Reservado] <= [Quantidade]"));
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.TransferenciaEstoque", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<int>("ProdutoId").HasColumnType("int");
                b.Property<int?>("OrigemId").HasColumnType("int");
                b.Property<int>("DestinoId").HasColumnType("int");
                b.Property<int>("UsuarioId").HasColumnType("int");
                b.Property<decimal>("Quantidade").HasPrecision(13, 3).HasColumnType("decimal(13,3)");
                b.Property<DateTime>("DataUtc").HasColumnType("datetime2");
                b.Property<string>("UsuarioNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                b.Property<string>("Motivo").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("OrigemDescricao").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("DestinoDescricao").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.HasKey("Id"); b.HasIndex("OrigemId"); b.HasIndex("DestinoId"); b.HasIndex("UsuarioId"); b.HasIndex("ProdutoId", "DataUtc");
                b.ToTable("TransferenciasEstoque", (string)null);
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.UnidadeMedida", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Sigla").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.Property<string>("Nome").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                b.Property<bool>("Ativo").HasColumnType("bit"); b.Property<bool>("Sistema").HasColumnType("bit");
                b.HasKey("Id"); b.HasIndex("Sigla").IsUnique(); b.ToTable("UnidadesMedida", (string)null);
                b.HasData(new { Id = 1, Sigla = "UN", Nome = "Unidade", Ativo = true, Sistema = true });
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Almoxarifado", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("Ativo").HasColumnType("bit"); b.HasKey("Id"); b.HasIndex("NomeNormalizado").IsUnique();
                b.ToTable("Almoxarifados", (string)null);
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PosicaoEstoque", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AlmoxarifadoId").HasColumnType("int");
                b.Property<string>("Corredor").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<string>("Estante").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<string>("Prateleira").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<string>("CorredorNormalizado").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<string>("EstanteNormalizada").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<string>("PrateleiraNormalizada").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                b.Property<bool>("Ativo").HasColumnType("bit"); b.HasKey("Id");
                b.HasIndex("AlmoxarifadoId", "CorredorNormalizado", "EstanteNormalizada", "PrateleiraNormalizada").IsUnique();
                b.ToTable("PosicoesEstoque", (string)null);
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.CentroCusto", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("Ativo").HasColumnType("bit"); b.HasKey("Id"); b.HasIndex("NomeNormalizado").IsUnique();
                b.ToTable("CentrosCusto", (string)null);
            });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.RequisicaoMaterial", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<int?>("CentroCustoId").HasColumnType("int");
                b.HasIndex("CentroCustoId");
                b.Property<string>("Finalidade").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<int>("SolicitanteId").HasColumnType("int");
                b.Property<string>("SolicitanteNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                b.Property<DateTime>("CriadoUtc").HasColumnType("datetime2");
                b.Property<int>("Situacao").HasColumnType("int");
                b.Property<DateTime?>("AprovadoUtc").HasColumnType("datetime2");
                b.Property<int?>("AprovadoPorId").HasColumnType("int");
                b.Property<string>("AprovadoPorNome").HasMaxLength(120).HasColumnType("nvarchar(120)");
                b.Property<DateTime?>("EncerradoUtc").HasColumnType("datetime2");
                b.Property<int?>("EncerradoPorId").HasColumnType("int");
                b.Property<string>("EncerradoPorNome").HasMaxLength(120).HasColumnType("nvarchar(120)");
                b.Property<string>("MotivoCancelamento").HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<byte[]>("Versao").IsRowVersion().HasColumnType("rowversion");
                b.HasKey("Id"); b.HasIndex("SolicitanteId"); b.HasIndex("AprovadoPorId"); b.HasIndex("EncerradoPorId");
                b.ToTable("RequisicoesMaterial", (string)null);
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.ItemRequisicaoMaterial", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                b.Property<long>("RequisicaoMaterialId").HasColumnType("bigint");
                b.Property<int>("ProdutoId").HasColumnType("int");
                b.Property<decimal>("Quantidade")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                b.Property<decimal>("QuantidadeEntregue")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                b.Property<decimal>("QuantidadeDevolvida")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                b.HasKey("Id"); b.HasIndex("ProdutoId"); b.HasIndex("RequisicaoMaterialId", "ProdutoId").IsUnique();
                b.ToTable("ItensRequisicaoMaterial", (string)null);
            });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("CategoriasProduto", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("Contato").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Email").HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("Telefone").HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.ItemPedidoCompra", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<long>("PedidoCompraId").HasColumnType("bigint");
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<decimal>("Quantidade")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.Property<decimal>("QuantidadeRecebida")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.HasKey("Id");
                    b.HasIndex("PedidoCompraId", "ProdutoId").IsUnique();
                    b.HasIndex("ProdutoId");
                    b.ToTable("ItensPedidoCompra", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PedidoCompra", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<int>("FornecedorId").HasColumnType("int");
                    b.Property<int>("Situacao").HasColumnType("int");
                    b.Property<DateTime>("CriadoUtc").HasColumnType("datetime2");
                    b.Property<int>("CriadoPorId").HasColumnType("int");
                    b.Property<string>("CriadoPorNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<DateTime?>("EncerradoUtc").HasColumnType("datetime2");
                    b.Property<int?>("EncerradoPorId").HasColumnType("int");
                    b.Property<string>("EncerradoPorNome").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("MotivoCancelamento").HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<byte[]>("Versao").IsRowVersion().HasColumnType("rowversion");
                    b.HasKey("Id");
                    b.HasIndex("FornecedorId");
                    b.HasIndex("CriadoPorId");
                    b.HasIndex("EncerradoPorId");
                    b.ToTable("PedidosCompra", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.InventarioFisico", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.Property<byte[]>("VersaoProduto").IsRequired().HasMaxLength(8).HasColumnType("varbinary(8)");
                    b.Property<decimal?>("QuantidadeContada")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.Property<int>("Situacao").HasColumnType("int");
                    b.Property<DateTime>("AbertoUtc").HasColumnType("datetime2");
                    b.Property<int>("AbertoPorId").HasColumnType("int");
                    b.Property<string>("AbertoPorNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<DateTime?>("EncerradoUtc").HasColumnType("datetime2");
                    b.Property<int?>("EncerradoPorId").HasColumnType("int");
                    b.Property<string>("EncerradoPorNome").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Motivo").HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<byte[]>("Versao").IsRowVersion().HasColumnType("rowversion");
                    b.HasKey("Id");
                    b.HasIndex("ProdutoId").IsUnique().HasFilter("[Situacao] = 1");
                    b.HasIndex("AbertoPorId");
                    b.HasIndex("EncerradoPorId");
                    b.ToTable("InventariosFisicos", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<DateTime>("DataUtc").HasColumnType("datetime2");
                    b.Property<DateTime>("DataEfetivaUtc").HasColumnType("datetime2");
                    b.Property<string>("DocumentoOrigem").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Motivo").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("UsuarioNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<int?>("UsuarioId").HasColumnType("int");
                    b.Property<decimal?>("CustoUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<decimal?>("SaldoApos")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.Property<string>("Observacao").HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<long?>("PedidoCompraId").HasColumnType("bigint");
                    b.Property<long?>("RequisicaoMaterialId").HasColumnType("bigint");
                    b.Property<Guid?>("EntregaId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("DevolucaoId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("RecebimentoId").HasColumnType("uniqueidentifier");
                    b.Property<decimal>("Quantidade")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.Property<int>("Tipo").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ProdutoId", "DataUtc");
                    b.HasIndex("UsuarioId");
                    b.HasIndex("PedidoCompraId", "RecebimentoId");
                    b.HasIndex("RequisicaoMaterialId", "EntregaId");
                    b.HasIndex("RequisicaoMaterialId", "DevolucaoId");
                    b.ToTable("MovimentosEstoque", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("PosicaoEstoqueId").HasColumnType("int");
                    b.Property<int>("UnidadeMedidaId").HasColumnType("int");
                    b.Property<int>("CategoriaId").HasColumnType("int");
                    b.Property<int?>("FornecedorId").HasColumnType("int");

                    b.Property<decimal>("Estoque")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<decimal>("EstoqueReservado")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");
                    b.Property<decimal>("EstoqueMinimo")
                        .HasPrecision(13, 3)
                        .HasColumnType("decimal(13,3)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .IsRequired()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");
                    b.HasIndex("UnidadeMedidaId");
                    b.HasIndex("CategoriaId");
                    b.HasIndex("PosicaoEstoqueId");
                    b.HasIndex("FornecedorId");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PerfilAcesso", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<bool>("CadastrarCategorias").HasColumnType("bit");
                    b.Property<bool>("CadastrarProdutos").HasColumnType("bit");
                    b.Property<bool>("GerenciarCategorias").HasColumnType("bit");
                    b.Property<bool>("GerenciarProdutos").HasColumnType("bit");
                    b.Property<bool>("MovimentarEstoque").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<bool>("Sistema").HasColumnType("bit");
                    b.Property<string>("VersaoSeguranca").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("PerfisAcesso", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<int>("PerfilId").HasColumnType("int");
                    b.Property<string>("SenhaHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("VersaoSeguranca").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("PerfilId");
                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.ItemPedidoCompra", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.PedidoCompra", null).WithMany("Itens")
                        .HasForeignKey("PedidoCompraId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", "Produto").WithMany()
                        .HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PedidoCompra", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Fornecedor", "Fornecedor").WithMany()
                        .HasForeignKey("FornecedorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("CriadoPorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("EncerradoPorId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("Fornecedor");
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.InventarioFisico", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", null).WithMany()
                        .HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("AbertoPorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("EncerradoPorId").OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.RequisicaoMaterial", null).WithMany().HasForeignKey("RequisicaoMaterialId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("GestaoEstoque.Domain.Entities.PedidoCompra", null)
                        .WithMany().HasForeignKey("PedidoCompraId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Produto", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.CategoriaProduto", "CategoriaProduto")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany().HasForeignKey("FornecedorId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("GestaoEstoque.Domain.Entities.PosicaoEstoque", "PosicaoEstoque").WithMany().HasForeignKey("PosicaoEstoqueId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("PosicaoEstoque");
                    b.HasOne("GestaoEstoque.Domain.Entities.UnidadeMedida", "UnidadeMedida").WithMany().HasForeignKey("UnidadeMedidaId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("UnidadeMedida");
                    b.Navigation("CategoriaProduto");
                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.PerfilAcesso", "PerfilAcesso")
                        .WithMany().HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("PerfilAcesso");
                });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.RequisicaoMaterial", b =>
            {
                b.HasOne("GestaoEstoque.Domain.Entities.CentroCusto", "CentroCusto").WithMany().HasForeignKey("CentroCustoId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("CentroCusto");
                b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany().HasForeignKey("SolicitanteId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany().HasForeignKey("AprovadoPorId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany().HasForeignKey("EncerradoPorId").OnDelete(DeleteBehavior.Restrict);
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.ItemRequisicaoMaterial", b =>
            {
                b.HasOne("GestaoEstoque.Domain.Entities.RequisicaoMaterial", null).WithMany("Itens").HasForeignKey("RequisicaoMaterialId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("GestaoEstoque.Domain.Entities.Produto", "Produto").WithMany().HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Produto");
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.RequisicaoMaterial", b => { b.Navigation("Itens"); });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PosicaoEstoque", b =>
            {
                b.HasOne("GestaoEstoque.Domain.Entities.Almoxarifado", "Almoxarifado").WithMany().HasForeignKey("AlmoxarifadoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Almoxarifado");
            });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.SaldoLocal", b =>
            {
                b.HasOne("GestaoEstoque.Domain.Entities.Produto", null).WithMany().HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("GestaoEstoque.Domain.Entities.PosicaoEstoque", "PosicaoEstoque").WithMany().HasForeignKey("PosicaoEstoqueId").OnDelete(DeleteBehavior.Restrict);
                b.Navigation("PosicaoEstoque");
            });
            modelBuilder.Entity("GestaoEstoque.Domain.Entities.TransferenciaEstoque", b =>
            {
                b.HasOne("GestaoEstoque.Domain.Entities.Produto", null).WithMany().HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany().HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("GestaoEstoque.Domain.Entities.PosicaoEstoque", null).WithMany().HasForeignKey("OrigemId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("GestaoEstoque.Domain.Entities.PosicaoEstoque", null).WithMany().HasForeignKey("DestinoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
