// <auto-generated />
using GestaoEstoque.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoEstoque.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestaoEstoqueDbContext))]
    partial class GestaoEstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("CategoriasProduto", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("Contato").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Email").HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("Telefone").HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.ItemPedidoCompra", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<long>("PedidoCompraId").HasColumnType("bigint");
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<int>("Quantidade").HasColumnType("int");
                    b.Property<int>("QuantidadeRecebida").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("PedidoCompraId", "ProdutoId").IsUnique();
                    b.HasIndex("ProdutoId");
                    b.ToTable("ItensPedidoCompra", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PedidoCompra", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<int>("FornecedorId").HasColumnType("int");
                    b.Property<int>("Situacao").HasColumnType("int");
                    b.Property<DateTime>("CriadoUtc").HasColumnType("datetime2");
                    b.Property<int>("CriadoPorId").HasColumnType("int");
                    b.Property<string>("CriadoPorNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<DateTime?>("EncerradoUtc").HasColumnType("datetime2");
                    b.Property<int?>("EncerradoPorId").HasColumnType("int");
                    b.Property<string>("EncerradoPorNome").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("MotivoCancelamento").HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<byte[]>("Versao").IsRowVersion().HasColumnType("rowversion");
                    b.HasKey("Id");
                    b.HasIndex("FornecedorId");
                    b.HasIndex("CriadoPorId");
                    b.HasIndex("EncerradoPorId");
                    b.ToTable("PedidosCompra", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.InventarioFisico", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<int>("SaldoInicial").HasColumnType("int");
                    b.Property<byte[]>("VersaoProduto").IsRequired().HasMaxLength(8).HasColumnType("varbinary(8)");
                    b.Property<int?>("QuantidadeContada").HasColumnType("int");
                    b.Property<int>("Situacao").HasColumnType("int");
                    b.Property<DateTime>("AbertoUtc").HasColumnType("datetime2");
                    b.Property<int>("AbertoPorId").HasColumnType("int");
                    b.Property<string>("AbertoPorNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<DateTime?>("EncerradoUtc").HasColumnType("datetime2");
                    b.Property<int?>("EncerradoPorId").HasColumnType("int");
                    b.Property<string>("EncerradoPorNome").HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Motivo").HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<byte[]>("Versao").IsRowVersion().HasColumnType("rowversion");
                    b.HasKey("Id");
                    b.HasIndex("ProdutoId").IsUnique().HasFilter("[Situacao] = 1");
                    b.HasIndex("AbertoPorId");
                    b.HasIndex("EncerradoPorId");
                    b.ToTable("InventariosFisicos", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<DateTime>("DataUtc").HasColumnType("datetime2");
                    b.Property<DateTime>("DataEfetivaUtc").HasColumnType("datetime2");
                    b.Property<string>("DocumentoOrigem").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Motivo").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("UsuarioNome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<int?>("UsuarioId").HasColumnType("int");
                    b.Property<decimal?>("CustoUnitario").HasPrecision(18, 4).HasColumnType("decimal(18,4)");
                    b.Property<int?>("SaldoApos").HasColumnType("int");
                    b.Property<string>("Observacao").HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<int>("Quantidade").HasColumnType("int");
                    b.Property<int>("Tipo").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ProdutoId", "DataUtc");
                    b.HasIndex("UsuarioId");
                    b.ToTable("MovimentosEstoque", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId").HasColumnType("int");
                    b.Property<int?>("FornecedorId").HasColumnType("int");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .IsRequired()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");
                    b.HasIndex("CategoriaId");
                    b.HasIndex("FornecedorId");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PerfilAcesso", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<bool>("CadastrarCategorias").HasColumnType("bit");
                    b.Property<bool>("CadastrarProdutos").HasColumnType("bit");
                    b.Property<bool>("GerenciarCategorias").HasColumnType("bit");
                    b.Property<bool>("GerenciarProdutos").HasColumnType("bit");
                    b.Property<bool>("MovimentarEstoque").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<bool>("Sistema").HasColumnType("bit");
                    b.Property<string>("VersaoSeguranca").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("PerfisAcesso", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<int>("PerfilId").HasColumnType("int");
                    b.Property<string>("SenhaHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("VersaoSeguranca").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("PerfilId");
                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.ItemPedidoCompra", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.PedidoCompra", null).WithMany("Itens")
                        .HasForeignKey("PedidoCompraId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", "Produto").WithMany()
                        .HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.PedidoCompra", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Fornecedor", "Fornecedor").WithMany()
                        .HasForeignKey("FornecedorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("CriadoPorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("EncerradoPorId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("Fornecedor");
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.InventarioFisico", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", null).WithMany()
                        .HasForeignKey("ProdutoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("AbertoPorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null).WithMany()
                        .HasForeignKey("EncerradoPorId").OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Produto", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.CategoriaProduto", "CategoriaProduto")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("GestaoEstoque.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany().HasForeignKey("FornecedorId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("CategoriaProduto");
                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.PerfilAcesso", "PerfilAcesso")
                        .WithMany().HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("PerfilAcesso");
                });
#pragma warning restore 612, 618
        }
    }
}
