// <auto-generated />
using GestaoEstoque.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoEstoque.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestaoEstoqueDbContext))]
    partial class GestaoEstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("NomeNormalizado").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("NomeNormalizado").IsUnique();
                    b.ToTable("CategoriasProduto", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
                    b.Property<DateTime>("DataUtc").HasColumnType("datetime2");
                    b.Property<string>("Observacao").HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<int>("ProdutoId").HasColumnType("int");
                    b.Property<int>("Quantidade").HasColumnType("int");
                    b.Property<int>("Tipo").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ProdutoId", "DataUtc");
                    b.ToTable("MovimentosEstoque", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId").HasColumnType("int");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .IsRequired()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");
                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("Ativo").HasColumnType("bit");
                    b.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("nvarchar(254)");
                    b.Property<string>("Nome").IsRequired().HasMaxLength(120).HasColumnType("nvarchar(120)");
                    b.Property<string>("Perfil").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("SenhaHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("VersaoSeguranca").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestaoEstoque.Domain.Entities.Produto", b =>
                {
                    b.HasOne("GestaoEstoque.Domain.Entities.CategoriaProduto", "CategoriaProduto")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("CategoriaProduto");
                });
#pragma warning restore 612, 618
        }
    }
}
